/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayDeque;
import java.util.Queue;
import java.util.Stack;
import javax.swing.JPanel;

import controller.*;
import model.Usuario;
import persistence.interfaces.*;
import persistence.mysql.*;

/**
 *
 * @author dener
 */
public class MainView extends javax.swing.JFrame {
    
    private final Stack<JPanel> screen;
    private Usuario loggedUser;

    private AlunoController alunoController;
    private DisciplinaController disciplinaController;
    private FeedController feedController;
    private ProfessorController professorController;
    private TopicoController topicoController;
    private UsuarioController usuarioController;

    private IAulaDAO aulaDAO;
    private IAvaliacaoDAO avaliacaoDAO;
    private IContratoDAO contratoDAO;
    private IDisciplinaDAO disciplinaDAO;
    private ITopicoAula topicoAula;
    private ITopicoDAO topicoDAO;
    private IUsuarioDAO usuarioDAO;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.screen = new Stack<>();

        aulaDAO = new AulaDAOMySQL();
        avaliacaoDAO = new AvaliacaoDAOMySQL();
        contratoDAO = new ContratoDAOMySQL();
        disciplinaDAO = new DisciplinaDAOMySQL();
        topicoAula = new TopicoAulaDAOMySQL();
        topicoDAO = new TopicoDAOMySQL();
        usuarioDAO = new UsuarioDAOMySQL();

        alunoController = new AlunoController(contratoDAO, usuarioDAO, aulaDAO);
        disciplinaController = new DisciplinaController(disciplinaDAO);
        feedController = new FeedController(aulaDAO, disciplinaDAO);
        professorController = new ProfessorController(aulaDAO, topicoDAO, usuarioDAO, disciplinaDAO, contratoDAO);
        topicoController = new TopicoController(usuarioDAO, topicoDAO);
        usuarioController = new UsuarioController(usuarioDAO, avaliacaoDAO);

        abrirLoginView();
    }
    
    public void abrirCadastrarUsuarioView() {
        JPanel view = new CadastrarUsuarioView(this, this.usuarioController);
        this.setContentPane(view);
        this.revalidate();
    }
    
    public void abrirAdicionarAulaView() {
        JPanel view = new AdicionarAulaView(this, loggedUser, topicoController,
                disciplinaController, professorController);
        // screen.push(view);
        this.setContentPane(view);
        this.revalidate();
    }
    
    private void abrirLoginView() {
        this.menu.setVisible(false);
        JPanel view = new LoginView(this, usuarioController);
        this.setContentPane(view);
        this.revalidate();
    }
    
    public void voltar() {
        // screen.pop();
        // JPanel view = screen.peek();
        JPanel view = new PaginaInicialView(this, feedController, usuarioController,
                topicoController, disciplinaController, alunoController);
        this.setContentPane(view);
        this.revalidate();
    }
    
    public void sair() {
        screen.clear();
        abrirLoginView();
        this.menu.setVisible(false);
    }
    
    public void abrirPaginaInicialView(Usuario user) {
        this.menu.setVisible(true);
        this.loggedUser = user;
        JPanel view = new PaginaInicialView(this, feedController, usuarioController,
                topicoController, disciplinaController, alunoController);
        // screen.add(view);
        this.setContentPane(view);
        this.revalidate();
        
        if(user.getTipoUsuario() == 0) {
            this.adicionarAula.setEnabled(false);
            this.contratosPendentes.setEnabled(false);
        } else {
            this.adicionarAula.setEnabled(true);
            this.contratosPendentes.setEnabled(true);
        }
    }
    
    public void abrirPerfilUsuarioView() {
        JPanel view = new PerfilUsuarioView(this, loggedUser);
        // screen.add(view);;
        this.setContentPane(view);
        this.revalidate();
    }
    
    public void abrirNotificacoesPendentesView() {
        JPanel view  = new ContratosPendentesView(this, loggedUser, professorController);
        
        this.setContentPane(view);
        this.revalidate();
    }
    
    public void abrirNotificacoesAceitasView() {
        JPanel view  = new ContratosAceitosView(this, loggedUser, professorController, alunoController);
        
        this.setContentPane(view);
        this.revalidate();
    }
    
    public Usuario getLoggedUser() {
        return this.loggedUser;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        acoes = new javax.swing.JMenu();
        paginaInicial = new javax.swing.JMenuItem();
        adicionarAula = new javax.swing.JMenuItem();
        contratosPendentes = new javax.swing.JMenuItem();
        contratosAceitos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        perfil = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 450));
        setResizable(false);

        contentPanel.setMaximumSize(new java.awt.Dimension(700, 400));
        contentPanel.setMinimumSize(new java.awt.Dimension(700, 400));
        contentPanel.setPreferredSize(new java.awt.Dimension(700, 400));
        contentPanel.setLayout(new javax.swing.OverlayLayout(contentPanel));

        acoes.setText("Ações");

        paginaInicial.setText("Pagina Inicial");
        paginaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginaInicialActionPerformed(evt);
            }
        });
        acoes.add(paginaInicial);

        adicionarAula.setText("Adicionar Aula");
        adicionarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarAulaActionPerformed(evt);
            }
        });
        acoes.add(adicionarAula);

        contratosPendentes.setText("Contratos Pendentes");
        contratosPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratosPendentesActionPerformed(evt);
            }
        });
        acoes.add(contratosPendentes);

        contratosAceitos.setText("Contratos Aceitos");
        contratosAceitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratosAceitosActionPerformed(evt);
            }
        });
        acoes.add(contratosAceitos);

        menu.add(acoes);

        jMenu2.setText("Conta");

        perfil.setText("Ver Perfil");
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });
        jMenu2.add(perfil);

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu2.add(sair);

        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarAulaActionPerformed
        abrirAdicionarAulaView();
    }//GEN-LAST:event_adicionarAulaActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        sair();
    }//GEN-LAST:event_sairActionPerformed

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
        abrirPerfilUsuarioView();
    }//GEN-LAST:event_perfilActionPerformed

    private void contratosPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratosPendentesActionPerformed
        abrirNotificacoesPendentesView();
    }//GEN-LAST:event_contratosPendentesActionPerformed

    private void paginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginaInicialActionPerformed
        abrirPaginaInicialView(loggedUser);
    }//GEN-LAST:event_paginaInicialActionPerformed

    private void contratosAceitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratosAceitosActionPerformed
        abrirNotificacoesAceitasView();
    }//GEN-LAST:event_contratosAceitosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acoes;
    private javax.swing.JMenuItem adicionarAula;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JMenuItem contratosAceitos;
    private javax.swing.JMenuItem contratosPendentes;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem paginaInicial;
    private javax.swing.JMenuItem perfil;
    private javax.swing.JMenuItem sair;
    // End of variables declaration//GEN-END:variables
}
