/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AlunoController;
import controller.DisciplinaController;
import controller.FeedController;
import controller.TopicoController;
import controller.UsuarioController;
import exceptions.DisciplinaNaoEncontrada;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.*;

import model.*;
import persistence.local.AulaDAO;
import persistence.local.ContratoDAO;
import persistence.local.UsuarioDAO;
import persistence.mysql.*;


/**
 *
 * @author dener
 */
public class PaginaInicialView extends javax.swing.JPanel {
    
    private final JFrame context;
    
    private ArrayList<Aula> arrAulas;
    private ArrayList<Aula> aulasMostradas;
    
    private final List<Professor> professores;
    private final List<Disciplina> disciplinas;
    private final List<Topico> topicos;
    
    private final DefaultListModel<String> modelTopicos;
    private final GenericComboModel<Professor> modelProfessorCombo;
    private final GenericComboModel<Topico> modelTopicosCombo;
    private final GenericComboModel<Disciplina> modelDisciplinaCombo;
    
    private final FeedController feedController;
    private final UsuarioController usuarioController;
    private final TopicoController topicoController;
    private final DisciplinaController disciplinaController;
    private final AlunoController alunoController;
    int index = 0;
    
    /**
     * Creates new form PaginaInicialView
     */
    public PaginaInicialView(JFrame context, FeedController feedController,
                             UsuarioController usuarioController, TopicoController topicoController,
                             DisciplinaController disciplinaController, AlunoController alunoController) {
        initComponents();
        this.context = context;
        modelTopicos = new DefaultListModel<>();
        
        this.feedController = feedController;
        this.usuarioController = usuarioController;
        this.topicoController = topicoController;
        this.disciplinaController = disciplinaController;
        this.alunoController = alunoController;

        this.professores = (ArrayList<Professor>) usuarioController.getProfessores();
        this.disciplinas = (ArrayList<Disciplina>) disciplinaController.getAll();
        this.topicos = (ArrayList<Topico>) topicoController.getAllTopicos();

        modelProfessorCombo = new GenericComboModel<Professor>(this.professores);
        modelTopicosCombo = new GenericComboModel<Topico>(this.topicos);
        modelDisciplinaCombo = new GenericComboModel<Disciplina>(this.disciplinas);

        arrAulas = (ArrayList<Aula>) feedController.getAllAulas();
        this.aulasMostradas = (ArrayList<Aula>) this.arrAulas.clone();
        descricao.setEditable(false);
        listTopicos.setModel(modelTopicos);
        
        filtroDisciplina.setModel(modelDisciplinaCombo);
        filtroTopico.setModel(modelTopicosCombo);
        filtroProfessor.setModel(modelProfessorCombo);
        
        updateAula(this.index);
        jLabel16.setVisible(false);
        
        Usuario u = ((MainView) context).getLoggedUser();
        if(u.getTipoUsuario() == 1) {
            this.contratar.setEnabled(false);
        }
    }
    
    private void updateAula(int index) {
        Aula aula = this.aulasMostradas.get(index);
        disciplina.setText(aula.getDisciplina().getNome());
        professor.setText(aula.getProfessor().getNome());
        valor.setText(String.format("%,.2f", aula.getValorHora()));

        this.modelTopicos.removeAllElements();

        for (Topico top : aula.getTopicos()) {
            this.modelTopicos.addElement(top.getDescricao());
        }

        descricao.setText(aula.getDescricao());
        verifyLimitAulas();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filtroDisciplina = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        filtroTopico = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        filtroProfessor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        valorMin = new javax.swing.JTextField();
        valorMax = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        resetar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        professor = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        disciplina = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        contratar = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        proximo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listTopicos = new javax.swing.JList<>();

        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aulas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 400));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Filtros");

        jLabel3.setText("Disciplina:");

        filtroDisciplina.setModel(new GenericComboModel<Disciplina>(this.disciplinas));
        filtroDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroDisciplinaActionPerformed(evt);
            }
        });

        jLabel4.setText("Tópico:");

        filtroTopico.setModel(new GenericComboModel<Topico>(this.topicos));

        jLabel5.setText("Professor:");

        filtroProfessor.setModel(new GenericComboModel<Professor>(this.professores));
        filtroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroProfessorActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor Min:");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        resetar.setText("Resetar Filtros");
        resetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor Max:");

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Não foi encontrado nenhuma Aula");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtroDisciplina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filtroTopico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filtroProfessor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(valorMin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(29, 29, 29))
                            .addComponent(valorMax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(resetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtroDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtroTopico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar)
                    .addComponent(resetar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(22, 22, 22))
        );

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane3.setViewportView(descricao);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Disciplina");

        valor.setText("jLabel7");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("Topicos");

        professor.setText("jLabel9");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Valor/hora");

        disciplina.setText("jLabel10");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel23.setText("Professor");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel24.setText("Descrição");

        contratar.setText("Contratar");
        contratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarActionPerformed(evt);
            }
        });

        anterior.setLabel("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        proximo.setLabel("Próximo");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        listTopicos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listTopicos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(professor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addComponent(contratar)
                                .addGap(119, 119, 119)
                                .addComponent(proximo)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(disciplina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(professor))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anterior)
                    .addComponent(proximo)
                    .addComponent(contratar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(323, 323, 323))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        arrAulas = (ArrayList<Aula>) this.feedController.getAllAulas();

        Topico topico = (Topico) filtroTopico.getSelectedItem();
        Disciplina disciplina = (Disciplina) filtroDisciplina.getSelectedItem();
        Professor professor = (Professor) filtroProfessor.getSelectedItem();

        if (disciplina != null) {
            try {
                arrAulas = (ArrayList<Aula>) this.feedController.getAulaPorDisciplina(disciplina.getNome());
            } catch (DisciplinaNaoEncontrada ex) {
                Logger.getLogger(PaginaInicialView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if (professor != null) {
            arrAulas =
                (ArrayList<Aula>) arrAulas.stream()
                        .filter(a -> a.getProfessor().getUsername().equals(professor.getUsername()))
                .collect(Collectors.toList());
        }

        List<Aula> toRemove = new ArrayList<>();

        if (topico != null) {
            int flag = 0;
            for (Aula arrAula : arrAulas) {
                flag=0;
                for (Topico top : arrAula.getTopicos()) {
                    if (top.getId()==topico.getId()) { 
                        flag=1;
                        break;
                    }
                }
                if(flag==0) {
                    toRemove.add(arrAula);
                }
            }
            arrAulas.removeAll(toRemove);
        }

        String ValorMin = valorMin.getText();
        String ValorMax = valorMax.getText();

        if (!ValorMin.isEmpty()) {
            double valorMin = Double.parseDouble(ValorMin);
            arrAulas = (ArrayList<Aula>) arrAulas.stream()
                    .filter(a -> a.getValorHora() >= valorMin)
                    .collect(Collectors.toList());
        }

        if (!ValorMax.isEmpty()) {
            double valorMax = Double.parseDouble(ValorMax);
            arrAulas = (ArrayList<Aula>) arrAulas.stream()
                    .filter(a -> a.getValorHora() <= valorMax)
                    .collect(Collectors.toList());
        }

        aulasMostradas = (ArrayList<Aula>) arrAulas.clone();
        if (aulasMostradas.size() != 0) {
            this.index = 0;
            updateAula(this.index);
            jLabel16.setVisible(false);
        } else {
            arrAulas = (ArrayList<Aula>) this.feedController.getAllAulas();
            aulasMostradas = (ArrayList<Aula>) arrAulas.clone();
            jLabel16.setVisible(true);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void resetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarActionPerformed
        filtroTopico.setSelectedIndex(-1);
        filtroDisciplina.setSelectedIndex(-1);
        filtroProfessor.setSelectedIndex(-1);
        valorMin.setText("");
        valorMax.setText("");
    }//GEN-LAST:event_resetarActionPerformed

    private void contratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarActionPerformed
        Usuario u = ((MainView) context).getLoggedUser();
        try {
            this.alunoController.negociarAula(u.getUsername(), aulasMostradas.get(index).getCodAula(), new Date(), new Date());
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_contratarActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        this.index--;
        updateAula(this.index);
    }//GEN-LAST:event_anteriorActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        // TODO add your handling code here:
        this.index++;
        updateAula(this.index);
    }//GEN-LAST:event_proximoActionPerformed

    private void filtroDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroDisciplinaActionPerformed

    private void filtroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroProfessorActionPerformed

    private void verifyLimitAulas() {
        if (this.index >= aulasMostradas.size()-1) {
            proximo.setEnabled(false);
        } else {
            proximo.setEnabled(true);
        }
        
        if (this.index <= 0) {
            anterior.setEnabled(false);
        } else {
            anterior.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton buscar;
    private javax.swing.JButton contratar;
    private javax.swing.JTextArea descricao;
    private javax.swing.JLabel disciplina;
    private javax.swing.JComboBox<Disciplina> filtroDisciplina;
    private javax.swing.JComboBox<Professor> filtroProfessor;
    private javax.swing.JComboBox<Topico> filtroTopico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listTopicos;
    private javax.swing.JLabel professor;
    private javax.swing.JButton proximo;
    private javax.swing.JButton resetar;
    private javax.swing.JLabel valor;
    private javax.swing.JTextField valorMax;
    private javax.swing.JTextField valorMin;
    // End of variables declaration//GEN-END:variables
}
